version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
    ports:
      - '5432:5432'
  web:
    environment:
      DATABASE_URL: postgres://postgres@db/postgres
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge