site_name: NCPWD Documentation
site_author: 'YAHYA-H'

repo_url: https://github.com/C3real-kill3r/NCPWD.git
pages:
  - index.md
  - Introduction:
    - 'What is NCPWD?': what_is_ncpwd.md
    - Quick Start: quick_start.md
    - History: history.md
    - FAQs: faq.md
  - Development:
    - How to Contribute: how_to_contribute.md
    - Release Process: release_process.md
    - Code of Conduct: code_of_conduct.md

theme: windmill